export const midtsBrand = {
  company: {
    name: 'MIDTS',
    website: 'midts.com',
    descriptor: 'Engineering Capacity On Demand',
    coverDescriptor: 'OVERFLOW ENGINEERING PARTNER',
    confidentialityLabel: 'CONFIDENTIAL',
  },
  colours: {
    black: '#050705',
    white: '#ffffff',
    gold: '#b4975a',
    grey: '#f7f7f5',
    border: '#d8d8d2',
    muted: '#4b5651',
    ink: '#111815',
    softGold: '#fff8e8',
  },
  document: {
    a4Width: '210mm',
    a4Height: '297mm',
    contentWidth: '170mm',
    previewClassName: 'min-h-screen bg-[#f7f7f5] px-4 py-10 print:bg-white print:p-0',
    pageClassName:
      'midts-document-page mx-auto flex h-[297mm] min-h-[297mm] w-full max-w-[210mm] flex-col overflow-hidden bg-white text-[#050705] shadow-[0_24px_80px_rgba(0,0,0,0.16)] print:m-0 print:w-[210mm] print:max-w-none print:shadow-none',
    bodyPageClassName: 'px-[20mm] py-[18mm]',
    bodyFrameClassName: 'flex flex-1 flex-col px-[20mm] py-[18mm]',
    bodyFirstSectionClassName: 'mt-12',
    bodySectionClassName: 'mt-6',
    bodyClosingClassName: 'mt-auto',
    coverPageClassName: 'bg-[#050705] px-[20mm] py-[18mm] text-white',
    headerClassName: 'flex items-start justify-between border-b border-[#d8d8d2] pb-5 text-xs uppercase text-[#4b5651]',
    headerDocumentTypeClassName: 'mt-1 text-[#b4975a]',
    headerReferenceClassName: 'font-semibold text-[#050705]',
    footerClassName:
      'mt-auto flex items-center justify-between border-t border-[#d8d8d2] pt-4 text-[10px] font-semibold uppercase text-[#4b5651]',
    coverFooterClassName:
      'flex items-center justify-between pt-5 text-[10px] font-semibold uppercase text-white/70',
  },
  spacing: {
    pagePreview: '40px',
    pageX: '20mm',
    pageY: '18mm',
    section: '10mm',
    block: '6mm',
  },
  typography: {
    coverTitleClassName: 'text-[68px] font-semibold leading-[0.95] tracking-normal',
    coverDescriptorClassName: 'text-[10px] font-semibold uppercase tracking-[0.18em]',
    coverMessageClassName: 'text-3xl font-semibold leading-tight',
    bodyClassName: 'text-base leading-8',
    bodyStackClassName: 'grid gap-4',
    sectionTitleClassName: 'text-4xl font-semibold leading-tight tracking-normal',
    metadataLabelClassName: 'text-[10px] font-semibold uppercase tracking-normal',
    metadataValueClassName: 'text-sm font-semibold leading-5',
    smallUppercaseClassName: 'text-[10px] font-semibold uppercase tracking-normal',
    contentTitleClassName: 'text-xl font-semibold text-[#050705]',
  },
  statusLabels: {
    draft: 'Draft',
    issued: 'Issued',
    approved: 'Approved',
    superseded: 'Superseded',
  },
  statusStyles: {
    draft: 'border-[#b4975a] bg-[#fff8e8] text-[#050705]',
    issued: 'border-[#050705] bg-[#050705] text-white',
    approved: 'border-[#050705] bg-white text-[#050705]',
    superseded: 'border-[#d8d8d2] bg-[#f7f7f5] text-[#4b5651]',
  },
  metadataStyles: {
    labelClassName: 'text-[10px] font-semibold uppercase tracking-normal text-[#b4975a]',
    valueClassName: 'text-sm font-semibold leading-6 text-[#050705]',
    inverseLabelClassName: 'text-[10px] font-semibold uppercase tracking-normal text-[#b4975a]',
    inverseValueClassName: 'text-sm font-semibold leading-5 text-white',
    gridClassName: 'grid border-y border-[#d8d8d2] text-sm sm:grid-cols-2',
    coverWrapperClassName: 'mt-auto border-y border-white/18 py-6',
    coverGridClassName: 'grid grid-cols-3 gap-6',
    itemClassName: 'border-b border-[#d8d8d2] py-4 last:border-b-0 sm:px-4 sm:first:pl-0',
    itemBorderClassName: 'sm:border-r',
  },
  componentStyles: {
    logoImageClassName: 'h-10 w-auto',
    logoImageInverseClassName: 'h-10 w-auto brightness-0 invert',
    logoDescriptorClassName: 'mt-4 text-[#b4975a]',
    sectionDividerClassName: 'mb-8 border-t border-[#050705] pt-5',
    sectionEyebrowClassName: 'text-[#b4975a]',
    contentBlockClassName: 'mb-10 max-w-[132mm]',
    commercialSummaryClassName: 'border-y border-[#050705]',
    commercialSummaryItemClassName: 'border-b border-[#d8d8d2] py-5 last:border-b-0 sm:px-5',
    commercialSummaryValueClassName: 'mt-3 text-lg font-semibold leading-7 text-[#050705]',
    signatureBlockClassName: 'grid gap-8 border-t border-[#d8d8d2] pt-8 sm:grid-cols-2',
    signatureLineClassName: 'h-12 border-b border-[#050705]',
    signaturePartyClassName: 'mt-4 text-xs font-semibold uppercase tracking-normal text-[#050705]',
    signatureMetaClassName: 'mt-1 text-[#4b5651]',
    coverDividerClassName: 'mt-8 h-px w-24 bg-[#b4975a]',
    coverBodyClassName: 'mt-8 max-w-[118mm]',
    coverMessageTextClassName: 'mt-4 text-lg leading-8 text-white/82',
  },
  documentTypeLabels: {
    documentSystem: 'Document Operating System',
    capabilityStatement: 'Capability Statement',
    proposal: 'Proposal',
    quote: 'Quote',
    sow: 'Statement of Work',
    invoice: 'Invoice',
    completionReport: 'Completion Report',
  },
} as const;

export type MidtsDocumentStatus = keyof typeof midtsBrand.statusLabels;
export type MidtsDocumentType = keyof typeof midtsBrand.documentTypeLabels;
